// svelte/src/App.svelte
<script lang="ts">
  import Item from "./components/Item.svelte";
  import SearchBox from "./components/SearchBox.svelte";
  import { itemMap } from "./data/items";

  let input = "";
  const itemIds = Array.from(itemMap.keys());
</script>

<div class="pokemonList">
  {#each itemIds as id}
    <Item {id} searchQuery={input} />
  {/each}
</div>

<footer>
  <p>
    Data is obtained from <a href="https://pokeapi.co/" rel="external"
      >PokéAPI</a
    >.
  </p>
</footer>

<div class="searchBox">
  <SearchBox bind:value={input} />
</div>

<style>
  .pokemonList {
    display: grid;
    grid-template-columns: repeat(auto-fill, 160px);
    grid-auto-rows: 4em;
    grid-gap: 20px;
    margin: 20px;
    justify-content: space-between;
  }

  .searchBox {
    position: fixed;
    top: 50vh;
    left: 50vw;
    transform: translate(-50%, -50%);
  }

  footer {
    text-align: center;
  }
</style>

// vue/src/App.vue
<script setup lang="ts">
  import { computed, ref } from 'vue';
import { itemMap } from './data/items';
import Item from './components/Item.vue';
import SearchBox from './components/SearchBox.vue';

  const input = ref('');

  const itemIds = computed(() => Array.from(itemMap.keys()))
</script>

<template>
  <div class="pokemonList">
    <Item v-for="id in itemIds" :key="id" :id="id" :search-query="input" />
  </div>
  <footer>
    <p>
      Data is obtained from
      <a href="https://pokeapi.co/" rel="external">
        PokéAPI
      </a>
      .
    </p>
  </footer>
  <div class="searchBox">
    <SearchBox v-model="input" />
  </div>
</template>

<style scoped>
.pokemonList {
    display: grid;
    grid-template-columns: repeat(auto-fill, 160px);
    grid-auto-rows: 4em;
    grid-gap: 20px;
    margin: 20px;
    justify-content: space-between;
}

.searchBox {
  position: fixed;
  top: 50vh;
  left: 50vw;
  transform: translate(-50%, -50%);
}

footer {
  text-align: center;
}
</style>
