// preact/src/components/Item/index.tsx
import { useMemo } from "preact/hooks";
import { itemMap } from "../../data/items";
import classes from "./Item.module.css";

type Props = {
  /**
   * ID of Item
   */
  id: string;
  /**
   * Search query, in lowercase
   */
  searchQuery: string;
};

export const Item: preact.FunctionComponent<Props> = ({ id, searchQuery }) => {
  const item = itemMap.get(id);
  if (!item) {
    return null;
  }

  const name = item.en.toLowerCase();
  const { nameMarked } = useMemo(() => {
    if (!searchQuery) {
      return {
        nameMarked: <span className={classes.name}>{item.en}</span>,
      };
    }
    const searchIndex = name.indexOf(searchQuery);
    if (searchIndex === -1) {
      return {
        nameMarked: (
          <span className={`${classes.name} ${classes.unmatchedName}`}>
            {item.en}
          </span>
        ),
      };
    }
    return {
      nameMarked: (
        <span className={classes.name}>
          {item.en.substring(0, searchIndex)}
          <mark>
            {item.en.substring(searchIndex, searchIndex + searchQuery.length)}
          </mark>
          {item.en.substring(searchIndex + searchQuery.length)}
        </span>
      ),
    };
  }, [name, item.en, searchQuery]);

  return (
    <div className={classes.wrapper}>
      <div className={classes.id}>{item.id}</div>
      <div>{nameMarked}</div>
      <div>{item.ja}</div>
    </div>
  );
};

// solidjs/src/components/Item/index.tsx
import { Component, createMemo, Show, Switch } from "solid-js";
import { itemMap } from "../../data/items";
import classes from "./Item.module.css";

type Props = {
  /**
   * ID of Item
   */
  id: string;
  /**
   * Search query, in lowercase
   */
  searchQuery: string;
};

export const Item: Component<Props> = (props) => {
  const item = () => itemMap.get(props.id);

  const nameMarked = createMemo(() => {
    const i = item();
    if (!i) {
      return undefined;
    }
    if (!props.searchQuery) {
      return {
        unmatched: false,
        prefix: i.en,
        mark: "",
        suffix: "",
      };
    }
    const name = i.en.toLowerCase();
    const searchIndex = name.indexOf(props.searchQuery);
    if (searchIndex === -1) {
      return {
        unmatched: true,
        prefix: i.en,
        mark: "",
        suffix: "",
      };
    }
    return {
      unmatched: false,
      prefix: i.en.substring(0, searchIndex),
      mark: i.en.substring(searchIndex, searchIndex + props.searchQuery.length),
      suffix: i.en.substring(searchIndex + props.searchQuery.length),
    };
  });

  return (
    <Show when={item() !== undefined && nameMarked() !== undefined}>
      <div classList={{ [classes.wrapper]: true }}>
        <div classList={{ [classes.id]: true }}>{item()!.id}</div>
        <div>
          <span
            classList={{
              [classes.name]: true,
              [classes.unmatchedName]: nameMarked()!.unmatched,
            }}
          >
            {nameMarked()!.prefix}
            <Show when={nameMarked()!.mark}>
              <mark>{nameMarked()!.mark}</mark>
            </Show>
            {nameMarked()!.suffix}
          </span>
        </div>
        <div>{item()!.ja}</div>
      </div>
    </Show>
  );
};
