// preact/src/App.tsx
import { useCallback, useState } from "preact/hooks";
import classes from "./App.module.css";
import { Item } from "./components/Item";
import { SearchBox } from "./components/SearchBox";
import { itemMap } from "./data/items";

export function App() {
  const [input, setInput] = useState("");
  const [searchQuery, setSearchQuery] = useState("");
  const onChange = useCallback((input: string) => {
    setInput(input);
    setSearchQuery(input.toLowerCase());
  }, []);

  return (
    <>
      <div className={classes.pokemonList}>
        {Array.from(itemMap.keys()).map((id) => {
          return <Item key={id} id={id} searchQuery={searchQuery} />;
        })}
      </div>
      <footer className={classes.footer}>
        <p>
          Data is obtained from{" "}
          <a href="https://pokeapi.co/" rel="external">
            PokéAPI
          </a>
          .
        </p>
      </footer>
      <div className={classes.searchBox}>
        <SearchBox input={input} onChange={onChange} />
      </div>
    </>
  );
}

// angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { itemMap } from "../data/items";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  input = "";
  searchQuery = "";

  itemIds = Array.from(itemMap.keys());

  onInput(value: string) {
    this.input = value;
    this.searchQuery = value.toLowerCase();
  }
}

<div class="pokemonList">
  <app-item
    *ngFor="let id of itemIds"
    [id]="id"
    [searchQuery]="searchQuery"
  ></app-item>
</div>
<footer>
  <p>
    Data is obtained from
    <a href="https://pokeapi.co/" rel="external"> PokéAPI </a>
    .
  </p>
</footer>
<div class="searchBox">
  <search-box [value]="input" (valueChange)="onInput($event)"></search-box>
</div>
