// solidjs/src/components/SearchBox/index.tsx
import { Component } from "solid-js";
import classes from "./SearchBox.module.css";

type Props = {
  /**
   * current input
   */
  input: string;
  /**
   * onChange handler
   */
  onChange: (input: string) => void;
};

export const SearchBox: Component<Props> = (props) => {
  return (
    <div classList={{ [classes.wrapper]: true }}>
      <input
        classList={{ [classes.input]: true }}
        value={props.input}
        onInput={(e) =>
          props.onChange((e.currentTarget as HTMLInputElement).value)
        }
      />
    </div>
  );
};

// preact/src/components/SearchBox/index.tsx
import classes from "./SearchBox.module.css";
type Props = {
  /**
   * current input
   */
  input: string;
  /**
   * onChange handler
   */
  onChange: (input: string) => void;
};

export const SearchBox: preact.FunctionComponent<Props> = ({
  input,
  onChange,
}) => {
  return (
    <div className={classes.wrapper}>
      <input
        className={classes.input}
        value={input}
        onInput={(e) => onChange(e.currentTarget.value)}
      />
    </div>
  );
};
